# Generated by Django 5.1 on 2024-08-11 22:46

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, verbose_name="Nome")),
                ("crm", models.IntegerField(verbose_name="CRM")),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+9999999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
            ],
            options={
                "verbose_name": "doctor",
                "verbose_name_plural": "doctors",
                "ordering": ["id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Especialidade",
                "verbose_name_plural": "Especialidades",
                "ordering": ["id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="Dia")),
                (
                    "schedule",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TimeField(verbose_name="Horários"), size=None
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda",
                        to="clinic.doctor",
                        verbose_name="Médico",
                    ),
                ),
            ],
            options={
                "verbose_name": "agenda",
                "verbose_name_plural": "agendas",
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="MedicalAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hourly", models.TimeField(verbose_name="Horários")),
                (
                    "scheduling_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de agendamento"
                    ),
                ),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_medical_appointment",
                        to="clinic.agenda",
                        verbose_name="Agenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "consultation",
                "verbose_name_plural": "consultations",
                "ordering": ["id"],
            },
        ),
    ]
