# Generated by Django 3.1.2 on 2020-10-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_auto_20201011_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horarios',
            new_name='horario',
        ),
    ]
