# Generated by Django 3.1.2 on 2020-10-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_auto_20201012_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(default=(23, 0)),
        ),
    ]
