# Generated by Django 3.1.2 on 2020-10-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='update_at',
        ),
    ]
