# Generated by Django 3.1.2 on 2020-10-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='name',
            new_name='nome',
        ),
    ]
